### ISSUE TITLE
Cannot find module 'request'

### ISSUE THREAD

**Issue by satokaz** [pizzacat83/codic-vscode-extension#1]
* VSCode Version: 1.9 Insiders 
* OS Version: macOS Sierra 10.12.2（16C67）

`request` モジュールが不足しているようで、そのままでは動作しませんでした。
$HOME/.vscode-insiders/extensions/pizzacat83.codic-0.0.1/ で、`npm install request` を実行し、Reload Window で有効になりましたので確認頂ければと。

![2017-01-07 17 09 35](https://cloud.githubusercontent.com/assets/13635244/21740412/cbf82606-d4fc-11e6-8af0-832bf4fd5841.png)

**Comment by pizzacat83** [comment]
ご指摘ありがとうございます。dependencies の設定が誤っていたので、修正いたしました。
