### ISSUE TITLE
グローバルに設定する単語の連結方法の情報をsettings.jsonへ保存するようにしてほしい

### ISSUE THREAD

**Issue by ten9miq** [pizzacat83/codic-vscode-extension#9]
codic: Set Which Case to Use Globallyにて単語の連結方法を設定しますが、
別のPCにVSCodeを入れて設定等を以前のPCと同期して作業する場合に`codic: Set Which Case to Use Globally`にて連結方法を設定しないと選択後の単語の挿入をしなくなります｡
そのことにすぐに気づけるのならいいのですが、しばらくの間なぜ動作しないか自分にはわかりませんでした。

ユーザー設定のsettings.jsonへ保存して置くことで別PCへ移行した場合にもsettings.jsonを同期すればいいので、
毎度`codic: Set Which Case to Use Globally`で設定する必要がなくなります。
ですのでsettings.jsonで`codic: Set Which Case to Use Globally`の情報を管理してほしいです。

もちろんですが、`codic: Set Which Case to Use Locally`の方は既存のままで良いかと思います｡

**Comment by pizzacat83** [comment]
確かにsettings.jsonに設定する方が便利ですね。実装した当初はsettings.jsonを拡張機能から書き換える方法が分からなかったのか無かったのか忘れましたが，そういった理由で現行の仕様にしていました。現在のマニュアルを確認してみたところ書き換えることができるようなので，コマンドパネルから書き換える機能は残したまま，設定の管理場所をsettings.jsonに移行しようと思います。

`Locally`の方もsettings.jsonに移行した方が複数PCでの作業で便利かと思ったので，`Locally`も`Globally`も各々のsettings.jsonで管理します。
